version: "3.7"

services:

    flask:
        image: webapp-flask
        build: ./flask
        restart: always
        volumes:
            - "./:/app"

    nginx:
        image: webapp-nginx
        build: ./nginx
        restart: always
        ports:
            - 5000:80
        depends_on:
            - flask
